### ISSUE TITLE
Time Problem with Auth

### ISSUE THREAD

**Issue by SchulzeStTSI** [jembi/openhim-mediator-utils#8]
Hello,

I had with the openhim core a lot of problems with 401 responses during the mediator registration. I debugged the core and this utils as well, and i found out that the auth-ts was not matching in http request header. The header differs in the hash calculation and in the interpretation in the core. I've added to line: 

https://github.com/jembi/openhim-mediator-utils/blob/master/auth.js#L41

simply toISOString() and everything works fine. I was able to register the mediator. I think this is a time zone problem (utils sending the date without timezone, core server converts it in the own zone). But i'm not 100% sure. Did you observe that kind of problems somewhere? My workarround for now is to copy all util classes.

**Comment by litlfred** [comment]
@rcrichton  @danfuterman  any ideas what may be the issue here?

**Comment by rcrichton** [comment]
Hi, thanks for reporting this. i think you have debugged this correctly, the OpenHIM docs [state the timestamp should be in ISO8601 format](http://openhim.org/docs/api/introduction/authentication#for-subsequent-requests-to-the-api). i think what is happening is that the OpenHIM server and the mediator are in two different time zones and when the OpenHIM tries to reproduce the hash to see if the token matches it uses it's timezone so the values don't match.

I will create a PR with this fix and try do a patch release.

**Comment by rcrichton** [comment]
@SchulzeStTSI this has now been release on npm. I hope that works well for you now - https://www.npmjs.com/package/openhim-mediator-utils/v/0.2.4

**Comment by SchulzeStTSI** [comment]
It works! Thank you very much:)

**Comment by litlfred** [comment]
Thanks!
